---
kind: pipeline
type: docker
name: Drone plugins CI

steps:
  - name: Build ansible plugin
    pull: always
    image: plugins/docker
    settings:
      registry: registry.b7w.me
      repo: registry.b7w.me/b7w/drone-plugin/ansible
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      context: ansible
      dockerfile: ansible/Dockerfile
      tags: latest
      bip: 173.17.1.2/24  # For docker in docker
    when:
      branch:
        - master
