---
kind: pipeline
type: docker
name: Drone plugins CI

steps:
  - name: Build docker-compose plugin
    pull: always
    image: plugins/docker
    settings:
      registry: registry.b7w.me
      repo: registry.b7w.me/b7w/drone-plugin/docker-compose
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest
      build_args:
        - HANDLER=docker-compose
      bip: 173.17.1.2/24  # For docker in docker
    when:
      branch:
        - master
